### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by linden2015** [linden2015/tilialog#1]
Version 0.11
Ubuntu 16.04

```
cd output
java com/tilialog/App &

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Couldn't read from settingsfile: settings.list.
	at com.tilialog.TlSettings.get(TlSettings.java:69)
	at com.tilialog.ui.MainFrame.buildUI(MainFrame.java:24)
	at com.tilialog.ui.MainFrame.<init>(MainFrame.java:15)
	at com.tilialog.App.run(App.java:17)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: settings.list (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at com.tilialog.TlTextFile.readAll(TlTextFile.java:21)
	at com.tilialog.TlSettings.get(TlSettings.java:58)
	... 17 more
```

**Comment by linden2015** [comment]
Fixed in v0.12
